[template]
prefix = "/service/ats"
owner = "postgres"
mode = "0644"
src = "pgbouncer.tmpl"
dest = "/etc/pgbouncer/pgbouncer.ini"

reload_cmd = "systemctl reload pgbouncer"

keys = [
    "/members/",
]