environment:
 
 
  matrix:
    - PYTHON: "C:\\Python36-x64"
 
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
 
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install -r requirements.txt --upgrade"
  - "pip install psycopg2-binary behave codacy-coverage coverage coveralls flake8 mock pytest-cov pytest setuptools --upgrade"

 
build: off
 
test_script:
  - "%PYTHON%\\python.exe setup.py test"
 
after_test:
#  - "python-codacy-coverage -r coverage.xml"
 
artifacts:
  - path: dist\*
