environment:
 
 
  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"
      DISTRIBUTIONS: "bdist_wheel"
 
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
 
install:
  - "%PYTHON%\\python.exe -m pip install wheel behave coverage flake8 mock pytest-cov pytest psycopg2-binary"
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptool"
 
build: off
 
test_script:
  - "%PYTHON%\\python.exe setup.py test"
 
after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"
 
artifacts:
  - path: dist\*
