class KazooException(Exception):
    ...
class ZookeeperError(KazooException):
    ...
class SessionExpiredError(ZookeeperError):
    ...
class ConnectionClosedError(SessionExpiredError):
    ...
class NoNodeError(ZookeeperError):
    ...
class NodeExistsError(ZookeeperError):
    ...
