from collections import namedtuple
class ACL(namedtuple('ACL', 'perms id')):
    ...
def make_acl(scheme: str, credential: str, read: bool = ..., write: bool = ..., create: bool = ..., delete: bool = ..., admin: bool = ..., all: bool = ...) -> ACL:
    ...
