--- Dockerfile	2015-09-03 09:24:16.355412216 +0200
+++ Dockerfile.test	2015-09-03 09:25:48.407879693 +0200
@@ -15,7 +15,9 @@
 ENV PGVERSION 9.4
 RUN apt-get install postgresql-${PGVERSION} -y
 RUN apt-get install python python-psycopg2 python-yaml python-requests python-dnspython python-pip python-mock -y
-RUN pip install patroni
+## We install prereqs from pypi, the package from testpypi
+RUN pip install --force-reinstall --upgrade kazoo boto python-etcd
+RUN pip install -i https://testpypi.python.org/pypi patroni
 
 
 ENV PATH /usr/lib/postgresql/${PGVERSION}/bin:$PATH
