from typing import Optional
class FAIL_REASON:
    SUCCESS = ...
    QUEUE_FULL = ...
    MISSING_LEADER = ...
    DISCARDED = ...
    NOT_LEADER = ...
    LEADER_CHANGED = ...
    REQUEST_DENIED = ...
class SyncObjConf:
    password: Optional[str]
    autoTickPeriod: int
    def __init__(self, **kwargs) -> None: ...
