from typing import Optional
class FAIL_REASON:
    SUCCESS = ...
    QUEUE_FULL = ...
    MISSING_LEADER = ...
    DISCARDED = ...
    NOT_LEADER = ...
    LEADER_CHANGED = ...
    REQUEST_DENIED = ...
class SyncObjConf:
    password: Optional[str]
    autoTickPeriod: int
    raftMinTimeout: float
    raftMaxTimeout: float
    connectionTimeout: float
    appendEntriesPeriod: float
    connectionRetryTime: float
    leaderFallbackTimeout: float
    def __init__(self, **kwargs) -> None: ...
    def validate(self) -> None: ...
