from typing import Optional
class DnsCachingResolver:
    def setTimeouts(self, cacheTime: float, failCacheTime: float) -> None: ...
    def resolve(self, hostname: str) -> Optional[str]: ...
def globalDnsResolver() -> DnsCachingResolver: ...
