from typing import Any, List, Optional, Union
from .node import TCPNode
class TcpUtility(Utility):
    def __init__(self, password: Optional[str] = None, timeout: float=900.0) -> None: ...
    def executeCommand(self, node: Union[str, TCPNode], command: List[Any]) -> Any: ...
