from enum import IntEnum
from typing import Any, Dict, List
class HRuleStyle(IntEnum):
    FRAME = 0
    ALL = 1
FRAME = HRuleStyle.FRAME
ALL = HRuleStyle.ALL
class PrettyTable:
    def __init__(self, *args: str, **kwargs: Any) -> None: ...
    def _stringify_hrule(self, options: Dict[str, Any], where: str = '') -> str: ...
    def _validate_field_names(self, *args: str, **kwargs: Any) -> None: ...
    @property
    def align(self) -> Dict[str, str]: ...
    @align.setter
    def align(self, val: str) -> None: ...
    def add_row(self, row: List[Any]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
