from typing import Any, Dict, List
FRAME = 1
ALL = 1
class PrettyTable:
    def __init__(self, *args: str, **kwargs: Any) -> None: ...
    def _stringify_hrule(self, options: Dict[str, Any], where: str = '') -> str: ...
    @property
    def align(self) -> Dict[str, str]: ...
    @align.setter
    def align(self, val: str) -> None: ...
    def add_row(self, row: List[Any]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
