apiVersion: v1
kind: Service
metadata:
  name: &cluster_name patronidemo-replica
  labels:
    application: patroni
    cluster-name: *cluster_name
    
spec:
  type: ClusterIP
  selector:
    application: patroni
    role: replica
    cluster-name: patronidemo
  ports:
  - port: 5432
    targetPort: 5432
