name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B104,B105,B108,B110,B310,B311,B404,B602,B603,B607,B608,B609 .
      - run: black --check . || true
      - run: codespell --ignore-words-list="datas" .
      - run: flake8 . --count --ignore=E111,E12,E226,E241,W503,W504
                      --max-complexity=54 --max-line-length=150 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt -r requirements.dev.txt
      - run: mypy --ignore-missing-imports . || true
      - run: pytest .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
